// Helper: generate a timestamp string HH:mm:ss.SSS offset by `minsAgo` minutes from now
const tsOffset = (minsAgo, secsAgo = 0) => {
  const d = new Date(Date.now() - (minsAgo * 60 + secsAgo) * 1000);
  const h = d.getHours().toString().padStart(2, '0');
  const m = d.getMinutes().toString().padStart(2, '0');
  const s = d.getSeconds().toString().padStart(2, '0');
  const ms = d.getMilliseconds().toString().padStart(3, '0');
  return `${h}:${m}:${s}.${ms}`;
};

export const initialAlarms = [
  {
    id: 1,
    timestamp: tsOffset(2),
    assetId: "PCC-33KV-BKR01",
    description: "Breaker TRIPPED – PCC 33 kV Incomer",
    severity: "critical",
    status: "unack",
    operator: "SYSTEM",
    isHistorical: false,
    category: "Protection",
    region: "Kajra, Bihar, India",
    voltageLevel: "33 kV",
    assetName: "PCC 33kV Incomer Breaker",
    currentState: "TRIPPED / OPEN",
    voltage: "0.0 kV",
    frequency: "50.00 Hz",
    activePower: "0.0 MW",
    reactivePower: "0.0 MVAr",
    temperature: "34 °C",
    commStatus: "Connected",
    raised: tsOffset(2),
    acknowledged: null,
    ackOperator: null,
    lastUpdate: tsOffset(2),
    notes: "",
    sopSteps: [false, false, false, false, false, false],
    sopProgress: 0
  },
  {
    id: 2,
    timestamp: tsOffset(3),
    assetId: "PV-INV-14",
    description: "Inverter OFFLINE",
    severity: "major",
    status: "active",
    operator: "SYSTEM",
    isHistorical: false,
    category: "Inverter",
    region: "Kajra, Bihar, India",
    voltageLevel: "33 kV",
    assetName: "PV Inverter Block 14",
    currentState: "OFFLINE / FAULT",
    voltage: "0.0 kV",
    frequency: "0.00 Hz",
    activePower: "0.0 MW",
    reactivePower: "0.0 MVAr",
    temperature: "72 °C",
    commStatus: "Lost",
    raised: tsOffset(3),
    acknowledged: null,
    ackOperator: null,
    lastUpdate: tsOffset(3),
    notes: "",
    sopSteps: [false, false, false, false, false, false],
    sopProgress: 0
  },
  {
    id: 3,
    timestamp: tsOffset(5),
    assetId: "PCC-33KV-BUS",
    description: "Active Power below Dispatch Setpoint",
    severity: "major",
    status: "active",
    operator: "SYSTEM",
    isHistorical: false,
    category: "Grid",
    region: "Kajra, Bihar, India",
    voltageLevel: "33 kV",
    assetName: "PCC 33kV Busbar A",
    currentState: "ACTIVE / UNDER_GEN",
    voltage: "32.8 kV",
    frequency: "49.85 Hz",
    activePower: "92.4 MW",
    reactivePower: "1.2 MVAr",
    temperature: "38 °C",
    commStatus: "Connected",
    raised: tsOffset(5),
    acknowledged: null,
    ackOperator: null,
    lastUpdate: tsOffset(5),
    notes: "",
    sopSteps: [false, false, false, false, false, false],
    sopProgress: 0
  },
  {
    id: 4,
    timestamp: tsOffset(10),
    assetId: "GRID-CONN",
    description: "Frequency LOW",
    severity: "minor",
    status: "ack",
    operator: "S. Chen",
    isHistorical: false,
    category: "Grid",
    region: "Kajra, Bihar, India",
    voltageLevel: "33 kV",
    assetName: "Grid Connection Point",
    currentState: "WARNING / FREQ_DROP",
    voltage: "32.9 kV",
    frequency: "49.78 Hz",
    activePower: "112.5 MW",
    reactivePower: "2.1 MVAr",
    temperature: null,
    commStatus: "Connected",
    raised: tsOffset(10),
    acknowledged: tsOffset(9, 35),
    ackOperator: "S. Chen",
    lastUpdate: tsOffset(9, 35),
    notes: "Grid frequency drop observed, waiting for governor response.",
    sopSteps: [true, true, false, false, false, false],
    sopProgress: 33
  },
  {
    id: 5,
    timestamp: tsOffset(15),
    assetId: "PF-CONTROLLER",
    description: "Power Factor below Set Limit",
    severity: "minor",
    status: "ack",
    operator: "S. Chen",
    isHistorical: false,
    category: "Controller",
    region: "Kajra, Bihar, India",
    voltageLevel: "33 kV",
    assetName: "Capacitor Bank PF Controller",
    currentState: "WARNING / LOW_PF",
    voltage: "33.1 kV",
    frequency: "50.01 Hz",
    activePower: "142.1 MW",
    reactivePower: "-6.2 MVAr",
    temperature: "31 °C",
    commStatus: "Connected",
    raised: tsOffset(15),
    acknowledged: tsOffset(14, 55),
    ackOperator: "S. Chen",
    lastUpdate: tsOffset(14, 55),
    notes: "Capacitor bank stage 4 switched on manually.",
    sopSteps: [true, true, true, false, false, false],
    sopProgress: 50
  },
  {
    id: 6,
    timestamp: tsOffset(22),
    assetId: "BESS-PCS-02",
    description: "Battery Discharge Rate HIGH",
    severity: "minor",
    status: "active",
    operator: "SYSTEM",
    isHistorical: false,
    category: "Battery",
    region: "Kajra, Bihar, India",
    voltageLevel: "33 kV",
    assetName: "BESS PCS Rack 02",
    currentState: "ACTIVE / OVER_DISCHARGE",
    voltage: "32.7 kV",
    frequency: "49.92 Hz",
    activePower: "-22.5 MW",
    reactivePower: "0.2 MVAr",
    temperature: "48 °C",
    commStatus: "Connected",
    raised: tsOffset(22),
    acknowledged: null,
    ackOperator: null,
    lastUpdate: tsOffset(22),
    notes: "",
    sopSteps: [false, false, false, false, false, false],
    sopProgress: 0
  },
  {
    id: 7,
    timestamp: tsOffset(35),
    assetId: "BMS-RACK-03",
    description: "Battery Temperature HIGH",
    severity: "info",
    status: "logged",
    operator: "SYSTEM",
    isHistorical: false,
    category: "BMS",
    region: "Kajra, Bihar, India",
    voltageLevel: "33 kV",
    assetName: "BESS Battery Module Rack 03",
    currentState: "WARNING / TEMP_HIGH",
    voltage: "33.0 kV",
    frequency: "50.00 Hz",
    activePower: "-10.0 MW",
    reactivePower: "0.0 MVAr",
    temperature: "52 °C",
    commStatus: "Connected",
    raised: tsOffset(35),
    acknowledged: tsOffset(34, 55),
    ackOperator: "SYSTEM",
    lastUpdate: tsOffset(34, 55),
    notes: "Thermal management active, exhaust fans started.",
    sopSteps: [true, true, true, true, true, false],
    sopProgress: 83
  },
  {
    id: 8,
    timestamp: tsOffset(50),
    assetId: "EMS-DISPATCH",
    description: "Active Power Setpoint Updated",
    severity: "info",
    status: "logged",
    operator: "SYSTEM",
    isHistorical: false,
    category: "Controller",
    region: "Kajra, Bihar, India",
    voltageLevel: "33 kV",
    assetName: "EMS Dispatch Console",
    currentState: "NORMAL / LOGGED",
    voltage: "33.0 kV",
    frequency: "50.02 Hz",
    activePower: "120.0 MW",
    reactivePower: "0.0 MVAr",
    temperature: null,
    commStatus: "Connected",
    raised: tsOffset(50),
    acknowledged: tsOffset(50),
    ackOperator: "SYSTEM",
    lastUpdate: tsOffset(50),
    notes: "Power setpoint changed from 115 MW to 120 MW by grid command dispatcher.",
    sopSteps: [true, true, true, true, true, true],
    sopProgress: 100
  },
  // Historical Alarms
  {
    id: 9,
    timestamp: tsOffset(70),
    assetId: "PV-ARRAY-01",
    description: "Solar Irradiance LOW",
    severity: "info",
    status: "logged",
    operator: "SYSTEM",
    isHistorical: true,
    category: "Solar",
    region: "Kajra, Bihar, India",
    voltageLevel: "33 kV",
    assetName: "PV Field Pyranometer Station 1",
    currentState: "NORMAL",
    voltage: "0.0 kV",
    frequency: "50.00 Hz",
    activePower: "14.2 MW",
    reactivePower: "0.0 MVAr",
    temperature: null,
    commStatus: "Connected",
    raised: tsOffset(70),
    acknowledged: tsOffset(70),
    ackOperator: "SYSTEM",
    lastUpdate: tsOffset(70),
    notes: "Irradiance dropped below 150 W/m² due to cloud cover.",
    sopSteps: [true, true, true, true, true, true],
    sopProgress: 100
  },
  {
    id: 10,
    timestamp: tsOffset(90),
    assetId: "BESS-PCS-01",
    description: "Battery Charge Cycle Completed",
    severity: "info",
    status: "logged",
    operator: "SYSTEM",
    isHistorical: true,
    category: "Battery",
    region: "Kajra, Bihar, India",
    voltageLevel: "33 kV",
    assetName: "BESS Charging PCS Unit 01",
    currentState: "NORMAL / STANDBY",
    voltage: "33.0 kV",
    frequency: "50.00 Hz",
    activePower: "0.0 MW",
    reactivePower: "0.0 MVAr",
    temperature: "35 °C",
    commStatus: "Connected",
    raised: tsOffset(90),
    acknowledged: tsOffset(90),
    ackOperator: "SYSTEM",
    lastUpdate: tsOffset(90),
    notes: "Charge complete, bank at 98.4% SOC.",
    sopSteps: [true, true, true, true, true, true],
    sopProgress: 100
  },
  {
    id: 11,
    timestamp: tsOffset(180),
    assetId: "PLANT-SYS",
    description: "Plant Synchronization Completed",
    severity: "info",
    status: "logged",
    operator: "SYSTEM",
    isHistorical: true,
    category: "Controller",
    region: "Kajra, Bihar, India",
    voltageLevel: "33 kV",
    assetName: "Kajra Plant Sync Module",
    currentState: "NORMAL / IN_SYNC",
    voltage: "33.2 kV",
    frequency: "50.00 Hz",
    activePower: "48.2 MW",
    reactivePower: "0.4 MVAr",
    temperature: null,
    commStatus: "Connected",
    raised: tsOffset(180),
    acknowledged: tsOffset(180),
    ackOperator: "SYSTEM",
    lastUpdate: tsOffset(180),
    notes: "Inverters phase sync validated, breaker closed.",
    sopSteps: [true, true, true, true, true, true],
    sopProgress: 100
  },
  {
    id: 12,
    timestamp: tsOffset(360),
    assetId: "BMS-NET",
    description: "Communication Restored – BMS Network",
    severity: "info",
    status: "logged",
    operator: "SYSTEM",
    isHistorical: true,
    category: "BMS",
    region: "Kajra, Bihar, India",
    voltageLevel: "33 kV",
    assetName: "BMS Network Switch Gateway",
    currentState: "NORMAL",
    voltage: "33.0 kV",
    frequency: "50.00 Hz",
    activePower: "0.0 MW",
    reactivePower: "0.0 MVAr",
    temperature: null,
    commStatus: "Connected",
    raised: tsOffset(360),
    acknowledged: tsOffset(360),
    ackOperator: "SYSTEM",
    lastUpdate: tsOffset(360),
    notes: "Switch rebooted, network link restored.",
    sopSteps: [true, true, true, true, true, true],
    sopProgress: 100
  }
];

export const initialTimelineEvents = [
  { id: 101, timestamp: tsOffset(2),    description: "Breaker TRIPPED – PCC 33 kV Incomer",        severity: "critical",   isHistorical: false },
  { id: 102, timestamp: tsOffset(2, 1), description: "Protection Trip Initiated – Feeder Relay",    severity: "critical",   isHistorical: false },
  { id: 103, timestamp: tsOffset(3),    description: "Inverter OFFLINE – PV-INV-14",                severity: "major",      isHistorical: false },
  { id: 104, timestamp: tsOffset(5),    description: "Active Power below Dispatch Setpoint",        severity: "major",      isHistorical: false },
  { id: 105, timestamp: tsOffset(10),   description: "Frequency LOW",                               severity: "minor",      isHistorical: false },
  { id: 106, timestamp: tsOffset(15),   description: "Power Factor below Set Limit",                severity: "minor",      isHistorical: false },
  { id: 107, timestamp: tsOffset(22),   description: "Battery Discharge Rate HIGH",                 severity: "info",       isHistorical: false },
  { id: 108, timestamp: tsOffset(35),   description: "Battery Temperature HIGH",                    severity: "historical", isHistorical: true  },
  { id: 109, timestamp: tsOffset(50),   description: "Active Power Setpoint Updated",               severity: "historical", isHistorical: true  },
  { id: 110, timestamp: tsOffset(70),   description: "Solar Irradiance LOW",                        severity: "historical", isHistorical: true  }
];
